# Generated by Django 4.1.7 on 2023-03-17 14:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="watchlist",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50, unique=True),
                null=True,
                size=None,
            ),
        ),
    ]
