# Generated by Django 4.1.7 on 2023-03-18 12:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_customuser_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="watchlist",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50, unique=True),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
